In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import statsmodels as sm
from pandas_profiling import ProfileReport
from sklearn.linear_model import Ridge,Lasso,RidgeCV,LassoCV,ElasticNet,ElasticNetCV, LinearRegression
from sklearn.model_selection import train_test_split 

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/srinivasav22/Graduate-Admission-Prediction/master/Admission_Predict_Ver1.1.csv')


In [3]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [4]:
# pf=ProfileReport(df)

In [5]:
# pf.to_widgets()

In [6]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [7]:
df["GRE Score"]=df['GRE Score'].fillna(df['GRE Score'].mean())
df['TOEFL Score']=df['TOEFL Score'].fillna(df['TOEFL Score'].mean())
df['University Rating']=df['University Rating'].fillna(df['University Rating'].mean())


In [8]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.472000   107.192000           3.114000    3.374000   
std    144.481833   11.295148     6.081868           1.143512    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  308.000000   103.000000           2.000000    2.500000   
50%    250.500000  317.000000   107.000000           3.000000    3.500000   
75%    375.250000  325.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

            LOR         CGPA    Research  Chance of Admit   
count  500.00000  500.000000  500.000000         500.00000  
mean     3.48400    8.576440    0.560000           0.72174  
std      0.92545    0.604813    0.496884           0.14114  
min      1.00000    6.800000    0.000000           0.34000  
25%      3.00000    8.127500    0.000000           0.63000  
50%      3.50000    8.560000    1.000000           0.72000  
75%      4.00000    9.040000    1.000000           0.82000  
max      5.00000    9.920000    1.000000           0.97000

In [9]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [10]:
df.drop(columns='Serial No.',inplace=True)

In [11]:
x=df.drop(columns=['Chance of Admit '])

In [12]:
y=df['Chance of Admit ']
from sklearn.preprocessing import StandardScaler


In [13]:
scalar=StandardScaler()

In [14]:
arr=scalar.fit_transform(x)
arr

array([[ 1.81923762,  1.77886545,  0.77558214, ...,  1.09894429,
         1.77680627,  0.88640526],
       [ 0.66714832, -0.03160087,  0.77558214, ...,  1.09894429,
         0.48585943,  0.88640526],
       [-0.0418297 , -0.52536441, -0.09979274, ...,  0.01730621,
        -0.95404281,  0.88640526],
       ...,
       [ 1.19888185,  2.10804114,  1.65095702, ...,  1.63976333,
         1.62785086,  0.88640526],
       [-0.39631872, -0.68995225,  0.77558214, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [ 0.93301508,  0.95592621,  0.77558214, ...,  1.09894429,
         0.76721964, -1.12815215]])

In [15]:
df1=pd.DataFrame(arr)
df1

0         1         2         3         4         5         6
0    1.819238  1.778865  0.775582  1.137360  1.098944  1.776806  0.886405
1    0.667148 -0.031601  0.775582  0.632315  1.098944  0.485859  0.886405
2   -0.041830 -0.525364 -0.099793 -0.377773  0.017306 -0.954043  0.886405
3    0.489904  0.462163 -0.099793  0.127271 -1.064332  0.154847  0.886405
4   -0.219074 -0.689952 -0.975168 -1.387862 -0.523513 -0.606480 -1.128152
..        ...       ...       ...       ...       ...       ...       ...
495  1.376126  0.132987  1.650957  1.137360  0.558125  0.734118  0.886405
496  1.819238  1.614278  1.650957  1.642404  1.639763  2.140919  0.886405
497  1.198882  2.108041  1.650957  1.137360  1.639763  1.627851  0.886405
498 -0.396319 -0.689952  0.775582  0.632315  1.639763 -0.242367 -1.128152
499  0.933015  0.955926  0.775582  1.137360  1.098944  0.767220 -1.128152

[500 rows x 7 columns]

In [16]:
df1.describe()

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   1.783684e-15  1.202149e-15 -6.439294e-17  2.926548e-16 -1.332268e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.346008e+00 -2.500419e+00 -1.850542e+00 -2.397950e+00 -2.686789e+00   
25%   -7.508077e-01 -6.899523e-01 -9.751676e-01 -8.828175e-01 -5.235128e-01   
50%    4.679255e-02 -3.160087e-02 -9.979274e-02  1.272712e-01  1.730621e-02   
75%    7.557706e-01  7.913384e-01  7.755821e-01  6.323155e-01  5.581253e-01   
max    2.085104e+00  2.108041e+00  1.650957e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.091971e-15 -2.202682e-16  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

In [17]:
arr

array([[ 1.81923762,  1.77886545,  0.77558214, ...,  1.09894429,
         1.77680627,  0.88640526],
       [ 0.66714832, -0.03160087,  0.77558214, ...,  1.09894429,
         0.48585943,  0.88640526],
       [-0.0418297 , -0.52536441, -0.09979274, ...,  0.01730621,
        -0.95404281,  0.88640526],
       ...,
       [ 1.19888185,  2.10804114,  1.65095702, ...,  1.63976333,
         1.62785086,  0.88640526],
       [-0.39631872, -0.68995225,  0.77558214, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [ 0.93301508,  0.95592621,  0.77558214, ...,  1.09894429,
         0.76721964, -1.12815215]])

In [18]:
# df1.profile_report()

In [19]:
#now check for multicollinearity
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [20]:
arr.shape

(500, 7)

In [21]:
for i in arr.shape:
    print(i)

500
7


In [22]:
[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

[4.464249139118506,
 3.9042133308172593,
 2.6210362171283177,
 2.8352103508865105,
 2.0335548605441005,
 4.777991929494217,
 1.4940078664337453]

In [23]:
#storing VIF in Data frame
vif_df=pd.DataFrame()
vif_df['vif']=[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]
vif_df['feature']=x.columns
vif_df

vif            feature
0  4.464249          GRE Score
1  3.904213        TOEFL Score
2  2.621036  University Rating
3  2.835210                SOP
4  2.033555               LOR 
5  4.777992               CGPA
6  1.494008           Research

In [24]:
#training and testing 

In [25]:
arr

array([[ 1.81923762,  1.77886545,  0.77558214, ...,  1.09894429,
         1.77680627,  0.88640526],
       [ 0.66714832, -0.03160087,  0.77558214, ...,  1.09894429,
         0.48585943,  0.88640526],
       [-0.0418297 , -0.52536441, -0.09979274, ...,  0.01730621,
        -0.95404281,  0.88640526],
       ...,
       [ 1.19888185,  2.10804114,  1.65095702, ...,  1.63976333,
         1.62785086,  0.88640526],
       [-0.39631872, -0.68995225,  0.77558214, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [ 0.93301508,  0.95592621,  0.77558214, ...,  1.09894429,
         0.76721964, -1.12815215]])

In [26]:
x_train,x_test,y_train,y_test=train_test_split(arr,y,test_size=0.15,random_state=100)

In [27]:
x_train

array([[ 0.84439283,  0.46216267, -0.09979274, ...,  0.01730621,
         0.30380282,  0.88640526],
       [-1.54840801, -1.18371579, -1.85054249, ..., -1.60515091,
        -1.13609942, -1.12815215],
       [ 0.66714832,  0.62675052, -0.09979274, ..., -2.14596996,
         0.35345462,  0.88640526],
       ...,
       [-1.01667449, -0.8545401 , -0.97516761, ..., -1.06433187,
        -0.65613201, -1.12815215],
       [-0.48494097, -0.8545401 , -0.09979274, ...,  0.55812525,
         0.10519562,  0.88640526],
       [-1.28254125, -0.8545401 , -1.85054249, ..., -2.14596996,
        -0.95404281, -1.12815215]])

In [28]:
lr=LinearRegression()

In [29]:
lr.fit(x_train,y_train)

LinearRegression()

In [30]:
import pickle
pickle.dump(lr,open('admission_linear.pickle','wb'))

In [31]:
!ls

Linear Regression M1.ipynb
ML2.ipynb
PCOS_infertility.csv
PCOS_without_infertility.ipynb
Research_PCOS.ipynb
Screenshot 2022-11-30 at 12.33.54 AM.png
Test.csv
Untitled.ipynb
admission_linear.pickle
admission_prediction.ipynb
advertising.csv
linear_reg.sav
logistic regression.ipynb
test.html


In [32]:
lr.predict([[1.81923762, 1.77886545, 0.77558214, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

array([0.94984219])

In [33]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
495        332          108                  5  4.5   4.0  9.02         1   
496        337          117                  5  5.0   5.0  9.87         1   
497        330          120                  5  4.5   5.0  9.56         1   
498        312          103                  4  4.0   5.0  8.43         0   
499        327          113                  4  4.5   4.5  9.04         0   

     Chance of Admit   
0                0.92  
1                0.76  
2                0.72  
3                0.80  
4                0.65  
..                ...  
495              0.87  
496              0.96  
497              0.93  
498              0.73  
499              0.84  

[500 rows x 8 columns]

In [34]:
test_1 = scalar.transform([[337,118,4,4.5,4.5,9.65,1]])

/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [35]:
test1

NameError: name 'test1' is not defined

In [ ]:
model=pickle.load(open('admission_linear.pickle','rb'))


In [ ]:
model.predict(test1)

In [ ]:
lr.score(x_test,y_test)

In [ ]:
x_test

In [ ]:
y_test

In [ ]:
def adj_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2
    

In [ ]:
adj_r2(x_test,y_test)

In [ ]:
lr.coef_

In [ ]:
lr.intercept_

In [ ]:
lassocv=LassoCV(cv=10,max_iter=2000000,normalize=True)
lassocv.fit(x_train,y_train)

In [ ]:
lassocv.alpha_

In [ ]:
lasso=Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

In [ ]:
lasso.score(x_test,y_test)